server:
  port: 8888

  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5



spring:
  application:
    name: catalog-service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://b1ackshadow:${CATALOG_CONFIG_TOKEN}@github.com/b1ackshadow/catalog-service-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

